<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN486037" failures="1" tests="3" name="my Test" time="0.08" errors="0" timestamp="2024-04-17T11:25:56 IST">
  <testcase classname="TestNG.TestNGListenersDemo" name="success" time="0.01"/>
  <testcase classname="TestNG.TestNGListenersDemo" name="fail" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at TestNG.TestNGListenersDemo.fail(TestNGListenersDemo.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- fail -->
  <testcase classname="TestNG.TestNGListenersDemo" name="skip" time="0.001">
    <skipped/>
  </testcase> <!-- skip -->
</testsuite> <!-- my Test -->
